/* This file was generated by SableCC (http://www.sablecc.org/). */

package lenguaje.node;

import java.util.*;
import lenguaje.analysis.*;

@SuppressWarnings("nls")
public final class AElseStatement extends PElseStatement
{
    private TElse _else_;
    private TLBracket _lBracket_;
    private final LinkedList<PLine> _line_ = new LinkedList<PLine>();
    private TRBracket _rBracket_;

    public AElseStatement()
    {
        // Constructor
    }

    public AElseStatement(
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") TLBracket _lBracket_,
        @SuppressWarnings("hiding") List<?> _line_,
        @SuppressWarnings("hiding") TRBracket _rBracket_)
    {
        // Constructor
        setElse(_else_);

        setLBracket(_lBracket_);

        setLine(_line_);

        setRBracket(_rBracket_);

    }

    @Override
    public Object clone()
    {
        return new AElseStatement(
            cloneNode(this._else_),
            cloneNode(this._lBracket_),
            cloneList(this._line_),
            cloneNode(this._rBracket_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseStatement(this);
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public TLBracket getLBracket()
    {
        return this._lBracket_;
    }

    public void setLBracket(TLBracket node)
    {
        if(this._lBracket_ != null)
        {
            this._lBracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBracket_ = node;
    }

    public LinkedList<PLine> getLine()
    {
        return this._line_;
    }

    public void setLine(List<?> list)
    {
        for(PLine e : this._line_)
        {
            e.parent(null);
        }
        this._line_.clear();

        for(Object obj_e : list)
        {
            PLine e = (PLine) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._line_.add(e);
        }
    }

    public TRBracket getRBracket()
    {
        return this._rBracket_;
    }

    public void setRBracket(TRBracket node)
    {
        if(this._rBracket_ != null)
        {
            this._rBracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBracket_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._else_)
            + toString(this._lBracket_)
            + toString(this._line_)
            + toString(this._rBracket_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._lBracket_ == child)
        {
            this._lBracket_ = null;
            return;
        }

        if(this._line_.remove(child))
        {
            return;
        }

        if(this._rBracket_ == child)
        {
            this._rBracket_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(this._lBracket_ == oldChild)
        {
            setLBracket((TLBracket) newChild);
            return;
        }

        for(ListIterator<PLine> i = this._line_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PLine) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._rBracket_ == oldChild)
        {
            setRBracket((TRBracket) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
