/* This file was generated by SableCC (http://www.sablecc.org/). */

package lenguaje.node;

import lenguaje.analysis.*;

@SuppressWarnings("nls")
public final class ASecondConditionCondition extends PCondition
{
    private PSecondCondition _secondCondition_;

    public ASecondConditionCondition()
    {
        // Constructor
    }

    public ASecondConditionCondition(
        @SuppressWarnings("hiding") PSecondCondition _secondCondition_)
    {
        // Constructor
        setSecondCondition(_secondCondition_);

    }

    @Override
    public Object clone()
    {
        return new ASecondConditionCondition(
            cloneNode(this._secondCondition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASecondConditionCondition(this);
    }

    public PSecondCondition getSecondCondition()
    {
        return this._secondCondition_;
    }

    public void setSecondCondition(PSecondCondition node)
    {
        if(this._secondCondition_ != null)
        {
            this._secondCondition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._secondCondition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._secondCondition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._secondCondition_ == child)
        {
            this._secondCondition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._secondCondition_ == oldChild)
        {
            setSecondCondition((PSecondCondition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
