/* This file was generated by SableCC (http://www.sablecc.org/). */

package lenguaje.node;

import lenguaje.analysis.*;

@SuppressWarnings("nls")
public final class AStrDeclarationAssignmentDeclaration extends PDeclaration
{
    private TStr _str_;
    private PAssignment _assignment_;
    private TSemicolon _semicolon_;

    public AStrDeclarationAssignmentDeclaration()
    {
        // Constructor
    }

    public AStrDeclarationAssignmentDeclaration(
        @SuppressWarnings("hiding") TStr _str_,
        @SuppressWarnings("hiding") PAssignment _assignment_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setStr(_str_);

        setAssignment(_assignment_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AStrDeclarationAssignmentDeclaration(
            cloneNode(this._str_),
            cloneNode(this._assignment_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStrDeclarationAssignmentDeclaration(this);
    }

    public TStr getStr()
    {
        return this._str_;
    }

    public void setStr(TStr node)
    {
        if(this._str_ != null)
        {
            this._str_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._str_ = node;
    }

    public PAssignment getAssignment()
    {
        return this._assignment_;
    }

    public void setAssignment(PAssignment node)
    {
        if(this._assignment_ != null)
        {
            this._assignment_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignment_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._str_)
            + toString(this._assignment_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._str_ == child)
        {
            this._str_ = null;
            return;
        }

        if(this._assignment_ == child)
        {
            this._assignment_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._str_ == oldChild)
        {
            setStr((TStr) newChild);
            return;
        }

        if(this._assignment_ == oldChild)
        {
            setAssignment((PAssignment) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
