/* This file was generated by SableCC (http://www.sablecc.org/). */

package work.node;

import work.analysis.*;

@SuppressWarnings("nls")
public final class ADoubleEqualsSecondCondition extends PSecondCondition
{
    private PItem1 _item1_;
    private TDoubleEquals _doubleEquals_;
    private PItem2 _item2_;

    public ADoubleEqualsSecondCondition()
    {
        // Constructor
    }

    public ADoubleEqualsSecondCondition(
        @SuppressWarnings("hiding") PItem1 _item1_,
        @SuppressWarnings("hiding") TDoubleEquals _doubleEquals_,
        @SuppressWarnings("hiding") PItem2 _item2_)
    {
        // Constructor
        setItem1(_item1_);

        setDoubleEquals(_doubleEquals_);

        setItem2(_item2_);

    }

    @Override
    public Object clone()
    {
        return new ADoubleEqualsSecondCondition(
            cloneNode(this._item1_),
            cloneNode(this._doubleEquals_),
            cloneNode(this._item2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADoubleEqualsSecondCondition(this);
    }

    public PItem1 getItem1()
    {
        return this._item1_;
    }

    public void setItem1(PItem1 node)
    {
        if(this._item1_ != null)
        {
            this._item1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._item1_ = node;
    }

    public TDoubleEquals getDoubleEquals()
    {
        return this._doubleEquals_;
    }

    public void setDoubleEquals(TDoubleEquals node)
    {
        if(this._doubleEquals_ != null)
        {
            this._doubleEquals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doubleEquals_ = node;
    }

    public PItem2 getItem2()
    {
        return this._item2_;
    }

    public void setItem2(PItem2 node)
    {
        if(this._item2_ != null)
        {
            this._item2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._item2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._item1_)
            + toString(this._doubleEquals_)
            + toString(this._item2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._item1_ == child)
        {
            this._item1_ = null;
            return;
        }

        if(this._doubleEquals_ == child)
        {
            this._doubleEquals_ = null;
            return;
        }

        if(this._item2_ == child)
        {
            this._item2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._item1_ == oldChild)
        {
            setItem1((PItem1) newChild);
            return;
        }

        if(this._doubleEquals_ == oldChild)
        {
            setDoubleEquals((TDoubleEquals) newChild);
            return;
        }

        if(this._item2_ == oldChild)
        {
            setItem2((PItem2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
