/* This file was generated by SableCC (http://www.sablecc.org/). */

package work.node;

import java.util.*;
import work.analysis.*;

@SuppressWarnings("nls")
public final class AFormatDecProgram extends PProgram
{
    private final LinkedList<PDeclaration> _declaration_ = new LinkedList<PDeclaration>();
    private final LinkedList<PLine> _line_ = new LinkedList<PLine>();

    public AFormatDecProgram()
    {
        // Constructor
    }

    public AFormatDecProgram(
        @SuppressWarnings("hiding") List<?> _declaration_,
        @SuppressWarnings("hiding") List<?> _line_)
    {
        // Constructor
        setDeclaration(_declaration_);

        setLine(_line_);

    }

    @Override
    public Object clone()
    {
        return new AFormatDecProgram(
            cloneList(this._declaration_),
            cloneList(this._line_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFormatDecProgram(this);
    }

    public LinkedList<PDeclaration> getDeclaration()
    {
        return this._declaration_;
    }

    public void setDeclaration(List<?> list)
    {
        for(PDeclaration e : this._declaration_)
        {
            e.parent(null);
        }
        this._declaration_.clear();

        for(Object obj_e : list)
        {
            PDeclaration e = (PDeclaration) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._declaration_.add(e);
        }
    }

    public LinkedList<PLine> getLine()
    {
        return this._line_;
    }

    public void setLine(List<?> list)
    {
        for(PLine e : this._line_)
        {
            e.parent(null);
        }
        this._line_.clear();

        for(Object obj_e : list)
        {
            PLine e = (PLine) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._line_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaration_)
            + toString(this._line_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaration_.remove(child))
        {
            return;
        }

        if(this._line_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDeclaration> i = this._declaration_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDeclaration) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PLine> i = this._line_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PLine) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
