/* This file was generated by SableCC (http://www.sablecc.org/). */

package work.node;

import work.analysis.*;

@SuppressWarnings("nls")
public final class AOrCondition extends PCondition
{
    private PCondition _condition_;
    private TOr _or_;
    private PSecondCondition _secondCondition_;

    public AOrCondition()
    {
        // Constructor
    }

    public AOrCondition(
        @SuppressWarnings("hiding") PCondition _condition_,
        @SuppressWarnings("hiding") TOr _or_,
        @SuppressWarnings("hiding") PSecondCondition _secondCondition_)
    {
        // Constructor
        setCondition(_condition_);

        setOr(_or_);

        setSecondCondition(_secondCondition_);

    }

    @Override
    public Object clone()
    {
        return new AOrCondition(
            cloneNode(this._condition_),
            cloneNode(this._or_),
            cloneNode(this._secondCondition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrCondition(this);
    }

    public PCondition getCondition()
    {
        return this._condition_;
    }

    public void setCondition(PCondition node)
    {
        if(this._condition_ != null)
        {
            this._condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condition_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    public PSecondCondition getSecondCondition()
    {
        return this._secondCondition_;
    }

    public void setSecondCondition(PSecondCondition node)
    {
        if(this._secondCondition_ != null)
        {
            this._secondCondition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._secondCondition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condition_)
            + toString(this._or_)
            + toString(this._secondCondition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condition_ == child)
        {
            this._condition_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        if(this._secondCondition_ == child)
        {
            this._secondCondition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condition_ == oldChild)
        {
            setCondition((PCondition) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(this._secondCondition_ == oldChild)
        {
            setSecondCondition((PSecondCondition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
