/* This file was generated by SableCC (http://www.sablecc.org/). */

package work.analysis;

import java.util.*;
import work.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPStart().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAStart(AStart node)
    {
        defaultIn(node);
    }

    public void outAStart(AStart node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStart(AStart node)
    {
        inAStart(node);
        if(node.getMainProgram() != null)
        {
            node.getMainProgram().apply(this);
        }
        outAStart(node);
    }

    public void inAMainProgram(AMainProgram node)
    {
        defaultIn(node);
    }

    public void outAMainProgram(AMainProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMainProgram(AMainProgram node)
    {
        inAMainProgram(node);
        if(node.getMain() != null)
        {
            node.getMain().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        if(node.getProgram() != null)
        {
            node.getProgram().apply(this);
        }
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        outAMainProgram(node);
    }

    public void inAFormatDecProgram(AFormatDecProgram node)
    {
        defaultIn(node);
    }

    public void outAFormatDecProgram(AFormatDecProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFormatDecProgram(AFormatDecProgram node)
    {
        inAFormatDecProgram(node);
        {
            List<PLine> copy = new ArrayList<PLine>(node.getLine());
            for(PLine e : copy)
            {
                e.apply(this);
            }
        }
        outAFormatDecProgram(node);
    }

    public void inAIntDeclarationAssignmentDeclaration(AIntDeclarationAssignmentDeclaration node)
    {
        defaultIn(node);
    }

    public void outAIntDeclarationAssignmentDeclaration(AIntDeclarationAssignmentDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntDeclarationAssignmentDeclaration(AIntDeclarationAssignmentDeclaration node)
    {
        inAIntDeclarationAssignmentDeclaration(node);
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getEquals() != null)
        {
            node.getEquals().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAIntDeclarationAssignmentDeclaration(node);
    }

    public void inAStringDeclarationAssignmentDeclaration(AStringDeclarationAssignmentDeclaration node)
    {
        defaultIn(node);
    }

    public void outAStringDeclarationAssignmentDeclaration(AStringDeclarationAssignmentDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringDeclarationAssignmentDeclaration(AStringDeclarationAssignmentDeclaration node)
    {
        inAStringDeclarationAssignmentDeclaration(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getEquals() != null)
        {
            node.getEquals().apply(this);
        }
        if(node.getStringLiteral() != null)
        {
            node.getStringLiteral().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAStringDeclarationAssignmentDeclaration(node);
    }

    public void inADoubleDeclarationAssignmentDeclaration(ADoubleDeclarationAssignmentDeclaration node)
    {
        defaultIn(node);
    }

    public void outADoubleDeclarationAssignmentDeclaration(ADoubleDeclarationAssignmentDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADoubleDeclarationAssignmentDeclaration(ADoubleDeclarationAssignmentDeclaration node)
    {
        inADoubleDeclarationAssignmentDeclaration(node);
        if(node.getDouble() != null)
        {
            node.getDouble().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getEquals() != null)
        {
            node.getEquals().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outADoubleDeclarationAssignmentDeclaration(node);
    }

    public void inAIntDeclarationDeclaration(AIntDeclarationDeclaration node)
    {
        defaultIn(node);
    }

    public void outAIntDeclarationDeclaration(AIntDeclarationDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntDeclarationDeclaration(AIntDeclarationDeclaration node)
    {
        inAIntDeclarationDeclaration(node);
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAIntDeclarationDeclaration(node);
    }

    public void inAStringDeclarationDeclaration(AStringDeclarationDeclaration node)
    {
        defaultIn(node);
    }

    public void outAStringDeclarationDeclaration(AStringDeclarationDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringDeclarationDeclaration(AStringDeclarationDeclaration node)
    {
        inAStringDeclarationDeclaration(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAStringDeclarationDeclaration(node);
    }

    public void inADoubleDeclarationDeclaration(ADoubleDeclarationDeclaration node)
    {
        defaultIn(node);
    }

    public void outADoubleDeclarationDeclaration(ADoubleDeclarationDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADoubleDeclarationDeclaration(ADoubleDeclarationDeclaration node)
    {
        inADoubleDeclarationDeclaration(node);
        if(node.getDouble() != null)
        {
            node.getDouble().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outADoubleDeclarationDeclaration(node);
    }

    public void inAStrAssignmentAssignment(AStrAssignmentAssignment node)
    {
        defaultIn(node);
    }

    public void outAStrAssignmentAssignment(AStrAssignmentAssignment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStrAssignmentAssignment(AStrAssignmentAssignment node)
    {
        inAStrAssignmentAssignment(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getEquals() != null)
        {
            node.getEquals().apply(this);
        }
        if(node.getStringLiteral() != null)
        {
            node.getStringLiteral().apply(this);
        }
        outAStrAssignmentAssignment(node);
    }

    public void inAExprAssignmentAssignment(AExprAssignmentAssignment node)
    {
        defaultIn(node);
    }

    public void outAExprAssignmentAssignment(AExprAssignmentAssignment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExprAssignmentAssignment(AExprAssignmentAssignment node)
    {
        inAExprAssignmentAssignment(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getEquals() != null)
        {
            node.getEquals().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAExprAssignmentAssignment(node);
    }

    public void inADeclarationLine(ADeclarationLine node)
    {
        defaultIn(node);
    }

    public void outADeclarationLine(ADeclarationLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclarationLine(ADeclarationLine node)
    {
        inADeclarationLine(node);
        if(node.getDeclaration() != null)
        {
            node.getDeclaration().apply(this);
        }
        outADeclarationLine(node);
    }

    public void inAPrintlnVarLine(APrintlnVarLine node)
    {
        defaultIn(node);
    }

    public void outAPrintlnVarLine(APrintlnVarLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintlnVarLine(APrintlnVarLine node)
    {
        inAPrintlnVarLine(node);
        if(node.getPrintln() != null)
        {
            node.getPrintln().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAPrintlnVarLine(node);
    }

    public void inAPrintlnStringLine(APrintlnStringLine node)
    {
        defaultIn(node);
    }

    public void outAPrintlnStringLine(APrintlnStringLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintlnStringLine(APrintlnStringLine node)
    {
        inAPrintlnStringLine(node);
        if(node.getPrintln() != null)
        {
            node.getPrintln().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getStringLiteral() != null)
        {
            node.getStringLiteral().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAPrintlnStringLine(node);
    }

    public void inAPrintlnNumberLine(APrintlnNumberLine node)
    {
        defaultIn(node);
    }

    public void outAPrintlnNumberLine(APrintlnNumberLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintlnNumberLine(APrintlnNumberLine node)
    {
        inAPrintlnNumberLine(node);
        if(node.getPrintln() != null)
        {
            node.getPrintln().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAPrintlnNumberLine(node);
    }

    public void inAPrintVarLine(APrintVarLine node)
    {
        defaultIn(node);
    }

    public void outAPrintVarLine(APrintVarLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintVarLine(APrintVarLine node)
    {
        inAPrintVarLine(node);
        if(node.getPrint() != null)
        {
            node.getPrint().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAPrintVarLine(node);
    }

    public void inAPrintStringLine(APrintStringLine node)
    {
        defaultIn(node);
    }

    public void outAPrintStringLine(APrintStringLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintStringLine(APrintStringLine node)
    {
        inAPrintStringLine(node);
        if(node.getPrint() != null)
        {
            node.getPrint().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getStringLiteral() != null)
        {
            node.getStringLiteral().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAPrintStringLine(node);
    }

    public void inAPrintNumberLine(APrintNumberLine node)
    {
        defaultIn(node);
    }

    public void outAPrintNumberLine(APrintNumberLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintNumberLine(APrintNumberLine node)
    {
        inAPrintNumberLine(node);
        if(node.getPrint() != null)
        {
            node.getPrint().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAPrintNumberLine(node);
    }

    public void inAInputLine(AInputLine node)
    {
        defaultIn(node);
    }

    public void outAInputLine(AInputLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInputLine(AInputLine node)
    {
        inAInputLine(node);
        if(node.getInput() != null)
        {
            node.getInput().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAInputLine(node);
    }

    public void inAIncrementLine(AIncrementLine node)
    {
        defaultIn(node);
    }

    public void outAIncrementLine(AIncrementLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIncrementLine(AIncrementLine node)
    {
        inAIncrementLine(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getInc() != null)
        {
            node.getInc().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAIncrementLine(node);
    }

    public void inADecrementLine(ADecrementLine node)
    {
        defaultIn(node);
    }

    public void outADecrementLine(ADecrementLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecrementLine(ADecrementLine node)
    {
        inADecrementLine(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getDec() != null)
        {
            node.getDec().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outADecrementLine(node);
    }

    public void inAFlowControlLine(AFlowControlLine node)
    {
        defaultIn(node);
    }

    public void outAFlowControlLine(AFlowControlLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFlowControlLine(AFlowControlLine node)
    {
        inAFlowControlLine(node);
        if(node.getFlowControl() != null)
        {
            node.getFlowControl().apply(this);
        }
        outAFlowControlLine(node);
    }

    public void inAAssignmentLine(AAssignmentLine node)
    {
        defaultIn(node);
    }

    public void outAAssignmentLine(AAssignmentLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignmentLine(AAssignmentLine node)
    {
        inAAssignmentLine(node);
        if(node.getAssignment() != null)
        {
            node.getAssignment().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAAssignmentLine(node);
    }

    public void inAIfFlowControl(AIfFlowControl node)
    {
        defaultIn(node);
    }

    public void outAIfFlowControl(AIfFlowControl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfFlowControl(AIfFlowControl node)
    {
        inAIfFlowControl(node);
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        {
            List<PLine> copy = new ArrayList<PLine>(node.getLine());
            for(PLine e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        outAIfFlowControl(node);
    }

    public void inAIfElseFlowControl(AIfElseFlowControl node)
    {
        defaultIn(node);
    }

    public void outAIfElseFlowControl(AIfElseFlowControl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfElseFlowControl(AIfElseFlowControl node)
    {
        inAIfElseFlowControl(node);
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        {
            List<PLine> copy = new ArrayList<PLine>(node.getLine());
            for(PLine e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        if(node.getElseStatement() != null)
        {
            node.getElseStatement().apply(this);
        }
        outAIfElseFlowControl(node);
    }

    public void inAWhileFlowControl(AWhileFlowControl node)
    {
        defaultIn(node);
    }

    public void outAWhileFlowControl(AWhileFlowControl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileFlowControl(AWhileFlowControl node)
    {
        inAWhileFlowControl(node);
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        {
            List<PLine> copy = new ArrayList<PLine>(node.getLine());
            for(PLine e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        outAWhileFlowControl(node);
    }

    public void inAElseStatement(AElseStatement node)
    {
        defaultIn(node);
    }

    public void outAElseStatement(AElseStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseStatement(AElseStatement node)
    {
        inAElseStatement(node);
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        {
            List<PLine> copy = new ArrayList<PLine>(node.getLine());
            for(PLine e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        outAElseStatement(node);
    }

    public void inASecondConditionCondition(ASecondConditionCondition node)
    {
        defaultIn(node);
    }

    public void outASecondConditionCondition(ASecondConditionCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASecondConditionCondition(ASecondConditionCondition node)
    {
        inASecondConditionCondition(node);
        if(node.getSecondCondition() != null)
        {
            node.getSecondCondition().apply(this);
        }
        outASecondConditionCondition(node);
    }

    public void inAAndCondition(AAndCondition node)
    {
        defaultIn(node);
    }

    public void outAAndCondition(AAndCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndCondition(AAndCondition node)
    {
        inAAndCondition(node);
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getAnd() != null)
        {
            node.getAnd().apply(this);
        }
        if(node.getSecondCondition() != null)
        {
            node.getSecondCondition().apply(this);
        }
        outAAndCondition(node);
    }

    public void inAOrCondition(AOrCondition node)
    {
        defaultIn(node);
    }

    public void outAOrCondition(AOrCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrCondition(AOrCondition node)
    {
        inAOrCondition(node);
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        if(node.getSecondCondition() != null)
        {
            node.getSecondCondition().apply(this);
        }
        outAOrCondition(node);
    }

    public void inADoubleEqualsSecondCondition(ADoubleEqualsSecondCondition node)
    {
        defaultIn(node);
    }

    public void outADoubleEqualsSecondCondition(ADoubleEqualsSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADoubleEqualsSecondCondition(ADoubleEqualsSecondCondition node)
    {
        inADoubleEqualsSecondCondition(node);
        if(node.getItem1() != null)
        {
            node.getItem1().apply(this);
        }
        if(node.getDoubleEquals() != null)
        {
            node.getDoubleEquals().apply(this);
        }
        if(node.getItem2() != null)
        {
            node.getItem2().apply(this);
        }
        outADoubleEqualsSecondCondition(node);
    }

    public void inANotEqualsSecondCondition(ANotEqualsSecondCondition node)
    {
        defaultIn(node);
    }

    public void outANotEqualsSecondCondition(ANotEqualsSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotEqualsSecondCondition(ANotEqualsSecondCondition node)
    {
        inANotEqualsSecondCondition(node);
        if(node.getItem1() != null)
        {
            node.getItem1().apply(this);
        }
        if(node.getNotEquals() != null)
        {
            node.getNotEquals().apply(this);
        }
        if(node.getItem2() != null)
        {
            node.getItem2().apply(this);
        }
        outANotEqualsSecondCondition(node);
    }

    public void inAGreaterSecondCondition(AGreaterSecondCondition node)
    {
        defaultIn(node);
    }

    public void outAGreaterSecondCondition(AGreaterSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGreaterSecondCondition(AGreaterSecondCondition node)
    {
        inAGreaterSecondCondition(node);
        if(node.getItem1() != null)
        {
            node.getItem1().apply(this);
        }
        if(node.getGreater() != null)
        {
            node.getGreater().apply(this);
        }
        if(node.getItem2() != null)
        {
            node.getItem2().apply(this);
        }
        outAGreaterSecondCondition(node);
    }

    public void inAGreaterEqSecondCondition(AGreaterEqSecondCondition node)
    {
        defaultIn(node);
    }

    public void outAGreaterEqSecondCondition(AGreaterEqSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGreaterEqSecondCondition(AGreaterEqSecondCondition node)
    {
        inAGreaterEqSecondCondition(node);
        if(node.getItem1() != null)
        {
            node.getItem1().apply(this);
        }
        if(node.getGreaterEq() != null)
        {
            node.getGreaterEq().apply(this);
        }
        if(node.getItem2() != null)
        {
            node.getItem2().apply(this);
        }
        outAGreaterEqSecondCondition(node);
    }

    public void inALessSecondCondition(ALessSecondCondition node)
    {
        defaultIn(node);
    }

    public void outALessSecondCondition(ALessSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALessSecondCondition(ALessSecondCondition node)
    {
        inALessSecondCondition(node);
        if(node.getItem1() != null)
        {
            node.getItem1().apply(this);
        }
        if(node.getLess() != null)
        {
            node.getLess().apply(this);
        }
        if(node.getItem2() != null)
        {
            node.getItem2().apply(this);
        }
        outALessSecondCondition(node);
    }

    public void inALessEqSecondCondition(ALessEqSecondCondition node)
    {
        defaultIn(node);
    }

    public void outALessEqSecondCondition(ALessEqSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALessEqSecondCondition(ALessEqSecondCondition node)
    {
        inALessEqSecondCondition(node);
        if(node.getItem1() != null)
        {
            node.getItem1().apply(this);
        }
        if(node.getLessEq() != null)
        {
            node.getLessEq().apply(this);
        }
        if(node.getItem2() != null)
        {
            node.getItem2().apply(this);
        }
        outALessEqSecondCondition(node);
    }

    public void inAExprItem1(AExprItem1 node)
    {
        defaultIn(node);
    }

    public void outAExprItem1(AExprItem1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExprItem1(AExprItem1 node)
    {
        inAExprItem1(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAExprItem1(node);
    }

    public void inAExprItem2(AExprItem2 node)
    {
        defaultIn(node);
    }

    public void outAExprItem2(AExprItem2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExprItem2(AExprItem2 node)
    {
        inAExprItem2(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAExprItem2(node);
    }

    public void inAPlusExpr(APlusExpr node)
    {
        defaultIn(node);
    }

    public void outAPlusExpr(APlusExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusExpr(APlusExpr node)
    {
        inAPlusExpr(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outAPlusExpr(node);
    }

    public void inAMinusExpr(AMinusExpr node)
    {
        defaultIn(node);
    }

    public void outAMinusExpr(AMinusExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMinusExpr(AMinusExpr node)
    {
        inAMinusExpr(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outAMinusExpr(node);
    }

    public void inATermExpr(ATermExpr node)
    {
        defaultIn(node);
    }

    public void outATermExpr(ATermExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATermExpr(ATermExpr node)
    {
        inATermExpr(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outATermExpr(node);
    }

    public void inAMultTerm(AMultTerm node)
    {
        defaultIn(node);
    }

    public void outAMultTerm(AMultTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultTerm(AMultTerm node)
    {
        inAMultTerm(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getUnary() != null)
        {
            node.getUnary().apply(this);
        }
        outAMultTerm(node);
    }

    public void inADivTerm(ADivTerm node)
    {
        defaultIn(node);
    }

    public void outADivTerm(ADivTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivTerm(ADivTerm node)
    {
        inADivTerm(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getUnary() != null)
        {
            node.getUnary().apply(this);
        }
        outADivTerm(node);
    }

    public void inAModTerm(AModTerm node)
    {
        defaultIn(node);
    }

    public void outAModTerm(AModTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAModTerm(AModTerm node)
    {
        inAModTerm(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getMod() != null)
        {
            node.getMod().apply(this);
        }
        if(node.getUnary() != null)
        {
            node.getUnary().apply(this);
        }
        outAModTerm(node);
    }

    public void inAUnaryTerm(AUnaryTerm node)
    {
        defaultIn(node);
    }

    public void outAUnaryTerm(AUnaryTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnaryTerm(AUnaryTerm node)
    {
        inAUnaryTerm(node);
        if(node.getUnary() != null)
        {
            node.getUnary().apply(this);
        }
        outAUnaryTerm(node);
    }

    public void inANegUnary(ANegUnary node)
    {
        defaultIn(node);
    }

    public void outANegUnary(ANegUnary node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegUnary(ANegUnary node)
    {
        inANegUnary(node);
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        if(node.getUnary() != null)
        {
            node.getUnary().apply(this);
        }
        outANegUnary(node);
    }

    public void inAFactorUnary(AFactorUnary node)
    {
        defaultIn(node);
    }

    public void outAFactorUnary(AFactorUnary node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFactorUnary(AFactorUnary node)
    {
        inAFactorUnary(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAFactorUnary(node);
    }

    public void inANumberFactor(ANumberFactor node)
    {
        defaultIn(node);
    }

    public void outANumberFactor(ANumberFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberFactor(ANumberFactor node)
    {
        inANumberFactor(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outANumberFactor(node);
    }

    public void inAVarFactor(AVarFactor node)
    {
        defaultIn(node);
    }

    public void outAVarFactor(AVarFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarFactor(AVarFactor node)
    {
        inAVarFactor(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAVarFactor(node);
    }

    public void inAGroupedFactor(AGroupedFactor node)
    {
        defaultIn(node);
    }

    public void outAGroupedFactor(AGroupedFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGroupedFactor(AGroupedFactor node)
    {
        inAGroupedFactor(node);
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        outAGroupedFactor(node);
    }
}
