/* This file was generated by SableCC (http://www.sablecc.org/). */

package work.parser;

import work.lexer.*;
import work.node.*;
import work.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PStart node1 = (PStart) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AStart */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce AMainProgram */
            {
                ArrayList<Object> list = new1();
                push(goTo(1), list, false);
            }
            break;
            case 2: /* reduce AAformatdecprogram1Program */
            {
                ArrayList<Object> list = new2();
                push(goTo(2), list, false);
            }
            break;
            case 3: /* reduce AAformatdecprogram2Program */
            {
                ArrayList<Object> list = new3();
                push(goTo(2), list, false);
            }
            break;
            case 4: /* reduce AAformatdecprogram3Program */
            {
                ArrayList<Object> list = new4();
                push(goTo(2), list, false);
            }
            break;
            case 5: /* reduce AAformatdecprogram4Program */
            {
                ArrayList<Object> list = new5();
                push(goTo(2), list, false);
            }
            break;
            case 6: /* reduce AIntDeclarationDeclaration */
            {
                ArrayList<Object> list = new6();
                push(goTo(3), list, false);
            }
            break;
            case 7: /* reduce AStringDeclarationDeclaration */
            {
                ArrayList<Object> list = new7();
                push(goTo(3), list, false);
            }
            break;
            case 8: /* reduce ADoubleDeclarationDeclaration */
            {
                ArrayList<Object> list = new8();
                push(goTo(3), list, false);
            }
            break;
            case 9: /* reduce AIntDeclarationAssignmentDeclaration */
            {
                ArrayList<Object> list = new9();
                push(goTo(3), list, false);
            }
            break;
            case 10: /* reduce AStringDeclarationAssignmentDeclaration */
            {
                ArrayList<Object> list = new10();
                push(goTo(3), list, false);
            }
            break;
            case 11: /* reduce ADoubleDeclarationAssignmentDeclaration */
            {
                ArrayList<Object> list = new11();
                push(goTo(3), list, false);
            }
            break;
            case 12: /* reduce APrintlnVarLine */
            {
                ArrayList<Object> list = new12();
                push(goTo(4), list, false);
            }
            break;
            case 13: /* reduce APrintlnStringLine */
            {
                ArrayList<Object> list = new13();
                push(goTo(4), list, false);
            }
            break;
            case 14: /* reduce APrintlnNumberLine */
            {
                ArrayList<Object> list = new14();
                push(goTo(4), list, false);
            }
            break;
            case 15: /* reduce APrintVarLine */
            {
                ArrayList<Object> list = new15();
                push(goTo(4), list, false);
            }
            break;
            case 16: /* reduce APrintStringLine */
            {
                ArrayList<Object> list = new16();
                push(goTo(4), list, false);
            }
            break;
            case 17: /* reduce APrintNumberLine */
            {
                ArrayList<Object> list = new17();
                push(goTo(4), list, false);
            }
            break;
            case 18: /* reduce AInputLine */
            {
                ArrayList<Object> list = new18();
                push(goTo(4), list, false);
            }
            break;
            case 19: /* reduce AFlowControlLine */
            {
                ArrayList<Object> list = new19();
                push(goTo(4), list, false);
            }
            break;
            case 20: /* reduce AAssignmentLine */
            {
                ArrayList<Object> list = new20();
                push(goTo(4), list, false);
            }
            break;
            case 21: /* reduce AAifflowcontrol1FlowControl */
            {
                ArrayList<Object> list = new21();
                push(goTo(5), list, false);
            }
            break;
            case 22: /* reduce AAifflowcontrol2FlowControl */
            {
                ArrayList<Object> list = new22();
                push(goTo(5), list, false);
            }
            break;
            case 23: /* reduce AAifelseflowcontrol1FlowControl */
            {
                ArrayList<Object> list = new23();
                push(goTo(5), list, false);
            }
            break;
            case 24: /* reduce AAifelseflowcontrol2FlowControl */
            {
                ArrayList<Object> list = new24();
                push(goTo(5), list, false);
            }
            break;
            case 25: /* reduce AAwhileflowcontrol1FlowControl */
            {
                ArrayList<Object> list = new25();
                push(goTo(5), list, false);
            }
            break;
            case 26: /* reduce AAwhileflowcontrol2FlowControl */
            {
                ArrayList<Object> list = new26();
                push(goTo(5), list, false);
            }
            break;
            case 27: /* reduce AAelsestatement1ElseStatement */
            {
                ArrayList<Object> list = new27();
                push(goTo(6), list, false);
            }
            break;
            case 28: /* reduce AAelsestatement2ElseStatement */
            {
                ArrayList<Object> list = new28();
                push(goTo(6), list, false);
            }
            break;
            case 29: /* reduce ASecondConditionCondition */
            {
                ArrayList<Object> list = new29();
                push(goTo(7), list, false);
            }
            break;
            case 30: /* reduce AAndCondition */
            {
                ArrayList<Object> list = new30();
                push(goTo(7), list, false);
            }
            break;
            case 31: /* reduce AOrCondition */
            {
                ArrayList<Object> list = new31();
                push(goTo(7), list, false);
            }
            break;
            case 32: /* reduce ADoubleEqualsSecondCondition */
            {
                ArrayList<Object> list = new32();
                push(goTo(8), list, false);
            }
            break;
            case 33: /* reduce ANotEqualsSecondCondition */
            {
                ArrayList<Object> list = new33();
                push(goTo(8), list, false);
            }
            break;
            case 34: /* reduce AGreaterSecondCondition */
            {
                ArrayList<Object> list = new34();
                push(goTo(8), list, false);
            }
            break;
            case 35: /* reduce AGreaterEqSecondCondition */
            {
                ArrayList<Object> list = new35();
                push(goTo(8), list, false);
            }
            break;
            case 36: /* reduce ALessSecondCondition */
            {
                ArrayList<Object> list = new36();
                push(goTo(8), list, false);
            }
            break;
            case 37: /* reduce ALessEqSecondCondition */
            {
                ArrayList<Object> list = new37();
                push(goTo(8), list, false);
            }
            break;
            case 38: /* reduce AGroupedSecondCondition */
            {
                ArrayList<Object> list = new38();
                push(goTo(8), list, false);
            }
            break;
            case 39: /* reduce AVarItem1 */
            {
                ArrayList<Object> list = new39();
                push(goTo(9), list, false);
            }
            break;
            case 40: /* reduce ANumberItem1 */
            {
                ArrayList<Object> list = new40();
                push(goTo(9), list, false);
            }
            break;
            case 41: /* reduce AStrItem1 */
            {
                ArrayList<Object> list = new41();
                push(goTo(9), list, false);
            }
            break;
            case 42: /* reduce AVarItem2 */
            {
                ArrayList<Object> list = new42();
                push(goTo(10), list, false);
            }
            break;
            case 43: /* reduce ANumberItem2 */
            {
                ArrayList<Object> list = new43();
                push(goTo(10), list, false);
            }
            break;
            case 44: /* reduce AStrItem2 */
            {
                ArrayList<Object> list = new44();
                push(goTo(10), list, false);
            }
            break;
            case 45: /* reduce AStrAssignmentAssignment */
            {
                ArrayList<Object> list = new45();
                push(goTo(11), list, false);
            }
            break;
            case 46: /* reduce AExprAssignmentAssignment */
            {
                ArrayList<Object> list = new46();
                push(goTo(11), list, false);
            }
            break;
            case 47: /* reduce AFactorExpr */
            {
                ArrayList<Object> list = new47();
                push(goTo(12), list, false);
            }
            break;
            case 48: /* reduce APlusExpr */
            {
                ArrayList<Object> list = new48();
                push(goTo(12), list, false);
            }
            break;
            case 49: /* reduce AMinusExpr */
            {
                ArrayList<Object> list = new49();
                push(goTo(12), list, false);
            }
            break;
            case 50: /* reduce ATermFactor */
            {
                ArrayList<Object> list = new50();
                push(goTo(13), list, false);
            }
            break;
            case 51: /* reduce AMultFactor */
            {
                ArrayList<Object> list = new51();
                push(goTo(13), list, false);
            }
            break;
            case 52: /* reduce ADivFactor */
            {
                ArrayList<Object> list = new52();
                push(goTo(13), list, false);
            }
            break;
            case 53: /* reduce AModFactor */
            {
                ArrayList<Object> list = new53();
                push(goTo(13), list, false);
            }
            break;
            case 54: /* reduce ANumberTerm */
            {
                ArrayList<Object> list = new54();
                push(goTo(14), list, false);
            }
            break;
            case 55: /* reduce AVarTerm */
            {
                ArrayList<Object> list = new55();
                push(goTo(14), list, false);
            }
            break;
            case 56: /* reduce AExprTerm */
            {
                ArrayList<Object> list = new56();
                push(goTo(14), list, false);
            }
            break;
            case 57: /* reduce ATerminal$Declaration */
            {
                ArrayList<Object> list = new57();
                push(goTo(15), list, true);
            }
            break;
            case 58: /* reduce ANonTerminal$Declaration */
            {
                ArrayList<Object> list = new58();
                push(goTo(15), list, true);
            }
            break;
            case 59: /* reduce ATerminal$Line */
            {
                ArrayList<Object> list = new59();
                push(goTo(16), list, true);
            }
            break;
            case 60: /* reduce ANonTerminal$Line */
            {
                ArrayList<Object> list = new60();
                push(goTo(16), list, true);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AStart */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStart pstartNode1;
        {
            // Block
        PMainProgram pmainprogramNode2;
        pmainprogramNode2 = (PMainProgram)nodeArrayList1.get(0);

        pstartNode1 = new AStart(pmainprogramNode2);
        }
	nodeList.add(pstartNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AMainProgram */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMainProgram pmainprogramNode1;
        {
            // Block
        TMain tmainNode2;
        TLPar tlparNode3;
        TRPar trparNode4;
        TLBracket tlbracketNode5;
        PProgram pprogramNode6;
        TRBracket trbracketNode7;
        tmainNode2 = (TMain)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        trparNode4 = (TRPar)nodeArrayList3.get(0);
        tlbracketNode5 = (TLBracket)nodeArrayList4.get(0);
        pprogramNode6 = (PProgram)nodeArrayList5.get(0);
        trbracketNode7 = (TRBracket)nodeArrayList6.get(0);

        pmainprogramNode1 = new AMainProgram(tmainNode2, tlparNode3, trparNode4, tlbracketNode5, pprogramNode6, trbracketNode7);
        }
	nodeList.add(pmainprogramNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AAformatdecprogram1Program */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PProgram pprogramNode1;
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        }
        {
            // Block
        }

        pprogramNode1 = new AFormatDecProgram(listNode2, listNode3);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AAformatdecprogram2Program */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        {
            // Block
        }

        pprogramNode1 = new AFormatDecProgram(listNode3, listNode4);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce AAformatdecprogram3Program */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        {
            // Block
        }
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList1.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pprogramNode1 = new AFormatDecProgram(listNode2, listNode4);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce AAformatdecprogram4Program */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pprogramNode1 = new AFormatDecProgram(listNode3, listNode5);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce AIntDeclarationDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TInt tintNode2;
        TVar tvarNode3;
        TSemicolon tsemicolonNode4;
        tintNode2 = (TInt)nodeArrayList1.get(0);
        tvarNode3 = (TVar)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new AIntDeclarationDeclaration(tintNode2, tvarNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AStringDeclarationDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TString tstringNode2;
        TVar tvarNode3;
        TSemicolon tsemicolonNode4;
        tstringNode2 = (TString)nodeArrayList1.get(0);
        tvarNode3 = (TVar)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new AStringDeclarationDeclaration(tstringNode2, tvarNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce ADoubleDeclarationDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TDouble tdoubleNode2;
        TVar tvarNode3;
        TSemicolon tsemicolonNode4;
        tdoubleNode2 = (TDouble)nodeArrayList1.get(0);
        tvarNode3 = (TVar)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new ADoubleDeclarationDeclaration(tdoubleNode2, tvarNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AIntDeclarationAssignmentDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TInt tintNode2;
        PAssignment passignmentNode3;
        TSemicolon tsemicolonNode4;
        tintNode2 = (TInt)nodeArrayList1.get(0);
        passignmentNode3 = (PAssignment)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new AIntDeclarationAssignmentDeclaration(tintNode2, passignmentNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce AStringDeclarationAssignmentDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TString tstringNode2;
        PAssignment passignmentNode3;
        TSemicolon tsemicolonNode4;
        tstringNode2 = (TString)nodeArrayList1.get(0);
        passignmentNode3 = (PAssignment)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new AStringDeclarationAssignmentDeclaration(tstringNode2, passignmentNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce ADoubleDeclarationAssignmentDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TDouble tdoubleNode2;
        PAssignment passignmentNode3;
        TSemicolon tsemicolonNode4;
        tdoubleNode2 = (TDouble)nodeArrayList1.get(0);
        passignmentNode3 = (PAssignment)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new ADoubleDeclarationAssignmentDeclaration(tdoubleNode2, passignmentNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce APrintlnVarLine */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLine plineNode1;
        {
            // Block
        TPrintln tprintlnNode2;
        TLPar tlparNode3;
        TVar tvarNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tprintlnNode2 = (TPrintln)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        tvarNode4 = (TVar)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        plineNode1 = new APrintlnVarLine(tprintlnNode2, tlparNode3, tvarNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(plineNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce APrintlnStringLine */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLine plineNode1;
        {
            // Block
        TPrintln tprintlnNode2;
        TLPar tlparNode3;
        TStringLiteral tstringliteralNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tprintlnNode2 = (TPrintln)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        tstringliteralNode4 = (TStringLiteral)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        plineNode1 = new APrintlnStringLine(tprintlnNode2, tlparNode3, tstringliteralNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(plineNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce APrintlnNumberLine */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLine plineNode1;
        {
            // Block
        TPrintln tprintlnNode2;
        TLPar tlparNode3;
        TNumber tnumberNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tprintlnNode2 = (TPrintln)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        tnumberNode4 = (TNumber)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        plineNode1 = new APrintlnNumberLine(tprintlnNode2, tlparNode3, tnumberNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(plineNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce APrintVarLine */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLine plineNode1;
        {
            // Block
        TPrint tprintNode2;
        TLPar tlparNode3;
        TVar tvarNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tprintNode2 = (TPrint)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        tvarNode4 = (TVar)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        plineNode1 = new APrintVarLine(tprintNode2, tlparNode3, tvarNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(plineNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce APrintStringLine */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLine plineNode1;
        {
            // Block
        TPrint tprintNode2;
        TLPar tlparNode3;
        TStringLiteral tstringliteralNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tprintNode2 = (TPrint)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        tstringliteralNode4 = (TStringLiteral)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        plineNode1 = new APrintStringLine(tprintNode2, tlparNode3, tstringliteralNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(plineNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce APrintNumberLine */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLine plineNode1;
        {
            // Block
        TPrint tprintNode2;
        TLPar tlparNode3;
        TNumber tnumberNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tprintNode2 = (TPrint)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        tnumberNode4 = (TNumber)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        plineNode1 = new APrintNumberLine(tprintNode2, tlparNode3, tnumberNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(plineNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce AInputLine */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLine plineNode1;
        {
            // Block
        TInput tinputNode2;
        TLPar tlparNode3;
        TVar tvarNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tinputNode2 = (TInput)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        tvarNode4 = (TVar)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        plineNode1 = new AInputLine(tinputNode2, tlparNode3, tvarNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(plineNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce AFlowControlLine */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLine plineNode1;
        {
            // Block
        PFlowControl pflowcontrolNode2;
        pflowcontrolNode2 = (PFlowControl)nodeArrayList1.get(0);

        plineNode1 = new AFlowControlLine(pflowcontrolNode2);
        }
	nodeList.add(plineNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce AAssignmentLine */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLine plineNode1;
        {
            // Block
        PAssignment passignmentNode2;
        TSemicolon tsemicolonNode3;
        passignmentNode2 = (PAssignment)nodeArrayList1.get(0);
        tsemicolonNode3 = (TSemicolon)nodeArrayList2.get(0);

        plineNode1 = new AAssignmentLine(passignmentNode2, tsemicolonNode3);
        }
	nodeList.add(plineNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce AAifflowcontrol1FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TIf tifNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBracket tlbracketNode6;
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        TRBracket trbracketNode8;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbracketNode6 = (TLBracket)nodeArrayList5.get(0);
        {
            // Block
        }
        trbracketNode8 = (TRBracket)nodeArrayList6.get(0);

        pflowcontrolNode1 = new AIfFlowControl(tifNode2, tlparNode3, pconditionNode4, trparNode5, tlbracketNode6, listNode7, trbracketNode8);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce AAifflowcontrol2FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TIf tifNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBracket tlbracketNode6;
        LinkedList<Object> listNode8 = new LinkedList<Object>();
        TRBracket trbracketNode9;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbracketNode6 = (TLBracket)nodeArrayList5.get(0);
        {
            // Block
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        listNode7 = (LinkedList)nodeArrayList6.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
        trbracketNode9 = (TRBracket)nodeArrayList7.get(0);

        pflowcontrolNode1 = new AIfFlowControl(tifNode2, tlparNode3, pconditionNode4, trparNode5, tlbracketNode6, listNode8, trbracketNode9);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce AAifelseflowcontrol1FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TIf tifNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBracket tlbracketNode6;
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        TRBracket trbracketNode8;
        PElseStatement pelsestatementNode9;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbracketNode6 = (TLBracket)nodeArrayList5.get(0);
        {
            // Block
        }
        trbracketNode8 = (TRBracket)nodeArrayList6.get(0);
        pelsestatementNode9 = (PElseStatement)nodeArrayList7.get(0);

        pflowcontrolNode1 = new AIfElseFlowControl(tifNode2, tlparNode3, pconditionNode4, trparNode5, tlbracketNode6, listNode7, trbracketNode8, pelsestatementNode9);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce AAifelseflowcontrol2FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TIf tifNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBracket tlbracketNode6;
        LinkedList<Object> listNode8 = new LinkedList<Object>();
        TRBracket trbracketNode9;
        PElseStatement pelsestatementNode10;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbracketNode6 = (TLBracket)nodeArrayList5.get(0);
        {
            // Block
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        listNode7 = (LinkedList)nodeArrayList6.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
        trbracketNode9 = (TRBracket)nodeArrayList7.get(0);
        pelsestatementNode10 = (PElseStatement)nodeArrayList8.get(0);

        pflowcontrolNode1 = new AIfElseFlowControl(tifNode2, tlparNode3, pconditionNode4, trparNode5, tlbracketNode6, listNode8, trbracketNode9, pelsestatementNode10);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce AAwhileflowcontrol1FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TWhile twhileNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBracket tlbracketNode6;
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        TRBracket trbracketNode8;
        twhileNode2 = (TWhile)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbracketNode6 = (TLBracket)nodeArrayList5.get(0);
        {
            // Block
        }
        trbracketNode8 = (TRBracket)nodeArrayList6.get(0);

        pflowcontrolNode1 = new AWhileFlowControl(twhileNode2, tlparNode3, pconditionNode4, trparNode5, tlbracketNode6, listNode7, trbracketNode8);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce AAwhileflowcontrol2FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TWhile twhileNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBracket tlbracketNode6;
        LinkedList<Object> listNode8 = new LinkedList<Object>();
        TRBracket trbracketNode9;
        twhileNode2 = (TWhile)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbracketNode6 = (TLBracket)nodeArrayList5.get(0);
        {
            // Block
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        listNode7 = (LinkedList)nodeArrayList6.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
        trbracketNode9 = (TRBracket)nodeArrayList7.get(0);

        pflowcontrolNode1 = new AWhileFlowControl(twhileNode2, tlparNode3, pconditionNode4, trparNode5, tlbracketNode6, listNode8, trbracketNode9);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce AAelsestatement1ElseStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElseStatement pelsestatementNode1;
        {
            // Block
        TElse telseNode2;
        TLBracket tlbracketNode3;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        TRBracket trbracketNode5;
        telseNode2 = (TElse)nodeArrayList1.get(0);
        tlbracketNode3 = (TLBracket)nodeArrayList2.get(0);
        {
            // Block
        }
        trbracketNode5 = (TRBracket)nodeArrayList3.get(0);

        pelsestatementNode1 = new AElseStatement(telseNode2, tlbracketNode3, listNode4, trbracketNode5);
        }
	nodeList.add(pelsestatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce AAelsestatement2ElseStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElseStatement pelsestatementNode1;
        {
            // Block
        TElse telseNode2;
        TLBracket tlbracketNode3;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        TRBracket trbracketNode6;
        telseNode2 = (TElse)nodeArrayList1.get(0);
        tlbracketNode3 = (TLBracket)nodeArrayList2.get(0);
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        trbracketNode6 = (TRBracket)nodeArrayList4.get(0);

        pelsestatementNode1 = new AElseStatement(telseNode2, tlbracketNode3, listNode5, trbracketNode6);
        }
	nodeList.add(pelsestatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce ASecondConditionCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCondition pconditionNode1;
        {
            // Block
        PSecondCondition psecondconditionNode2;
        psecondconditionNode2 = (PSecondCondition)nodeArrayList1.get(0);

        pconditionNode1 = new ASecondConditionCondition(psecondconditionNode2);
        }
	nodeList.add(pconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce AAndCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCondition pconditionNode1;
        {
            // Block
        PCondition pconditionNode2;
        TAnd tandNode3;
        PSecondCondition psecondconditionNode4;
        pconditionNode2 = (PCondition)nodeArrayList1.get(0);
        tandNode3 = (TAnd)nodeArrayList2.get(0);
        psecondconditionNode4 = (PSecondCondition)nodeArrayList3.get(0);

        pconditionNode1 = new AAndCondition(pconditionNode2, tandNode3, psecondconditionNode4);
        }
	nodeList.add(pconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce AOrCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCondition pconditionNode1;
        {
            // Block
        PCondition pconditionNode2;
        TOr torNode3;
        PSecondCondition psecondconditionNode4;
        pconditionNode2 = (PCondition)nodeArrayList1.get(0);
        torNode3 = (TOr)nodeArrayList2.get(0);
        psecondconditionNode4 = (PSecondCondition)nodeArrayList3.get(0);

        pconditionNode1 = new AOrCondition(pconditionNode2, torNode3, psecondconditionNode4);
        }
	nodeList.add(pconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce ADoubleEqualsSecondCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSecondCondition psecondconditionNode1;
        {
            // Block
        PItem1 pitem1Node2;
        TDoubleEquals tdoubleequalsNode3;
        PItem2 pitem2Node4;
        pitem1Node2 = (PItem1)nodeArrayList1.get(0);
        tdoubleequalsNode3 = (TDoubleEquals)nodeArrayList2.get(0);
        pitem2Node4 = (PItem2)nodeArrayList3.get(0);

        psecondconditionNode1 = new ADoubleEqualsSecondCondition(pitem1Node2, tdoubleequalsNode3, pitem2Node4);
        }
	nodeList.add(psecondconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce ANotEqualsSecondCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSecondCondition psecondconditionNode1;
        {
            // Block
        PItem1 pitem1Node2;
        TNotEquals tnotequalsNode3;
        PItem2 pitem2Node4;
        pitem1Node2 = (PItem1)nodeArrayList1.get(0);
        tnotequalsNode3 = (TNotEquals)nodeArrayList2.get(0);
        pitem2Node4 = (PItem2)nodeArrayList3.get(0);

        psecondconditionNode1 = new ANotEqualsSecondCondition(pitem1Node2, tnotequalsNode3, pitem2Node4);
        }
	nodeList.add(psecondconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce AGreaterSecondCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSecondCondition psecondconditionNode1;
        {
            // Block
        PItem1 pitem1Node2;
        TGreater tgreaterNode3;
        PItem2 pitem2Node4;
        pitem1Node2 = (PItem1)nodeArrayList1.get(0);
        tgreaterNode3 = (TGreater)nodeArrayList2.get(0);
        pitem2Node4 = (PItem2)nodeArrayList3.get(0);

        psecondconditionNode1 = new AGreaterSecondCondition(pitem1Node2, tgreaterNode3, pitem2Node4);
        }
	nodeList.add(psecondconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce AGreaterEqSecondCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSecondCondition psecondconditionNode1;
        {
            // Block
        PItem1 pitem1Node2;
        TGreaterEq tgreatereqNode3;
        PItem2 pitem2Node4;
        pitem1Node2 = (PItem1)nodeArrayList1.get(0);
        tgreatereqNode3 = (TGreaterEq)nodeArrayList2.get(0);
        pitem2Node4 = (PItem2)nodeArrayList3.get(0);

        psecondconditionNode1 = new AGreaterEqSecondCondition(pitem1Node2, tgreatereqNode3, pitem2Node4);
        }
	nodeList.add(psecondconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce ALessSecondCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSecondCondition psecondconditionNode1;
        {
            // Block
        PItem1 pitem1Node2;
        TLess tlessNode3;
        PItem2 pitem2Node4;
        pitem1Node2 = (PItem1)nodeArrayList1.get(0);
        tlessNode3 = (TLess)nodeArrayList2.get(0);
        pitem2Node4 = (PItem2)nodeArrayList3.get(0);

        psecondconditionNode1 = new ALessSecondCondition(pitem1Node2, tlessNode3, pitem2Node4);
        }
	nodeList.add(psecondconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce ALessEqSecondCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSecondCondition psecondconditionNode1;
        {
            // Block
        PItem1 pitem1Node2;
        TLessEq tlesseqNode3;
        PItem2 pitem2Node4;
        pitem1Node2 = (PItem1)nodeArrayList1.get(0);
        tlesseqNode3 = (TLessEq)nodeArrayList2.get(0);
        pitem2Node4 = (PItem2)nodeArrayList3.get(0);

        psecondconditionNode1 = new ALessEqSecondCondition(pitem1Node2, tlesseqNode3, pitem2Node4);
        }
	nodeList.add(psecondconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce AGroupedSecondCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSecondCondition psecondconditionNode1;
        {
            // Block
        TLPar tlparNode2;
        PCondition pconditionNode3;
        TRPar trparNode4;
        tlparNode2 = (TLPar)nodeArrayList1.get(0);
        pconditionNode3 = (PCondition)nodeArrayList2.get(0);
        trparNode4 = (TRPar)nodeArrayList3.get(0);

        psecondconditionNode1 = new AGroupedSecondCondition(tlparNode2, pconditionNode3, trparNode4);
        }
	nodeList.add(psecondconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce AVarItem1 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PItem1 pitem1Node1;
        {
            // Block
        TVar tvarNode2;
        tvarNode2 = (TVar)nodeArrayList1.get(0);

        pitem1Node1 = new AVarItem1(tvarNode2);
        }
	nodeList.add(pitem1Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce ANumberItem1 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PItem1 pitem1Node1;
        {
            // Block
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pitem1Node1 = new ANumberItem1(tnumberNode2);
        }
	nodeList.add(pitem1Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce AStrItem1 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PItem1 pitem1Node1;
        {
            // Block
        TStringLiteral tstringliteralNode2;
        tstringliteralNode2 = (TStringLiteral)nodeArrayList1.get(0);

        pitem1Node1 = new AStrItem1(tstringliteralNode2);
        }
	nodeList.add(pitem1Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce AVarItem2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PItem2 pitem2Node1;
        {
            // Block
        TVar tvarNode2;
        tvarNode2 = (TVar)nodeArrayList1.get(0);

        pitem2Node1 = new AVarItem2(tvarNode2);
        }
	nodeList.add(pitem2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce ANumberItem2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PItem2 pitem2Node1;
        {
            // Block
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pitem2Node1 = new ANumberItem2(tnumberNode2);
        }
	nodeList.add(pitem2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce AStrItem2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PItem2 pitem2Node1;
        {
            // Block
        TStringLiteral tstringliteralNode2;
        tstringliteralNode2 = (TStringLiteral)nodeArrayList1.get(0);

        pitem2Node1 = new AStrItem2(tstringliteralNode2);
        }
	nodeList.add(pitem2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce AStrAssignmentAssignment */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAssignment passignmentNode1;
        {
            // Block
        TVar tvarNode2;
        TEquals tequalsNode3;
        TStringLiteral tstringliteralNode4;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tequalsNode3 = (TEquals)nodeArrayList2.get(0);
        tstringliteralNode4 = (TStringLiteral)nodeArrayList3.get(0);

        passignmentNode1 = new AStrAssignmentAssignment(tvarNode2, tequalsNode3, tstringliteralNode4);
        }
	nodeList.add(passignmentNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce AExprAssignmentAssignment */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAssignment passignmentNode1;
        {
            // Block
        TVar tvarNode2;
        TEquals tequalsNode3;
        PExpr pexprNode4;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tequalsNode3 = (TEquals)nodeArrayList2.get(0);
        pexprNode4 = (PExpr)nodeArrayList3.get(0);

        passignmentNode1 = new AExprAssignmentAssignment(tvarNode2, tequalsNode3, pexprNode4);
        }
	nodeList.add(passignmentNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce AFactorExpr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        PFactor pfactorNode2;
        pfactorNode2 = (PFactor)nodeArrayList1.get(0);

        pexprNode1 = new AFactorExpr(pfactorNode2);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce APlusExpr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        PExpr pexprNode2;
        TPlus tplusNode3;
        PFactor pfactorNode4;
        pexprNode2 = (PExpr)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        pfactorNode4 = (PFactor)nodeArrayList3.get(0);

        pexprNode1 = new APlusExpr(pexprNode2, tplusNode3, pfactorNode4);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new49() /* reduce AMinusExpr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        PExpr pexprNode2;
        TMinus tminusNode3;
        PFactor pfactorNode4;
        pexprNode2 = (PExpr)nodeArrayList1.get(0);
        tminusNode3 = (TMinus)nodeArrayList2.get(0);
        pfactorNode4 = (PFactor)nodeArrayList3.get(0);

        pexprNode1 = new AMinusExpr(pexprNode2, tminusNode3, pfactorNode4);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new50() /* reduce ATermFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        PTerm ptermNode2;
        ptermNode2 = (PTerm)nodeArrayList1.get(0);

        pfactorNode1 = new ATermFactor(ptermNode2);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new51() /* reduce AMultFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        PFactor pfactorNode2;
        TMult tmultNode3;
        PTerm ptermNode4;
        pfactorNode2 = (PFactor)nodeArrayList1.get(0);
        tmultNode3 = (TMult)nodeArrayList2.get(0);
        ptermNode4 = (PTerm)nodeArrayList3.get(0);

        pfactorNode1 = new AMultFactor(pfactorNode2, tmultNode3, ptermNode4);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new52() /* reduce ADivFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        PFactor pfactorNode2;
        TDiv tdivNode3;
        PTerm ptermNode4;
        pfactorNode2 = (PFactor)nodeArrayList1.get(0);
        tdivNode3 = (TDiv)nodeArrayList2.get(0);
        ptermNode4 = (PTerm)nodeArrayList3.get(0);

        pfactorNode1 = new ADivFactor(pfactorNode2, tdivNode3, ptermNode4);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new53() /* reduce AModFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        PFactor pfactorNode2;
        TMod tmodNode3;
        PTerm ptermNode4;
        pfactorNode2 = (PFactor)nodeArrayList1.get(0);
        tmodNode3 = (TMod)nodeArrayList2.get(0);
        ptermNode4 = (PTerm)nodeArrayList3.get(0);

        pfactorNode1 = new AModFactor(pfactorNode2, tmodNode3, ptermNode4);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new54() /* reduce ANumberTerm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        ptermNode1 = new ANumberTerm(tnumberNode2);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new55() /* reduce AVarTerm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TVar tvarNode2;
        tvarNode2 = (TVar)nodeArrayList1.get(0);

        ptermNode1 = new AVarTerm(tvarNode2);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new56() /* reduce AExprTerm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TLPar tlparNode2;
        PExpr pexprNode3;
        TRPar trparNode4;
        tlparNode2 = (TLPar)nodeArrayList1.get(0);
        pexprNode3 = (PExpr)nodeArrayList2.get(0);
        trparNode4 = (TRPar)nodeArrayList3.get(0);

        ptermNode1 = new AExprTerm(tlparNode2, pexprNode3, trparNode4);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new57() /* reduce ATerminal$Declaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PDeclaration pdeclarationNode1;
        pdeclarationNode1 = (PDeclaration)nodeArrayList1.get(0);
	if(pdeclarationNode1 != null)
	{
	  listNode2.add(pdeclarationNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new58() /* reduce ANonTerminal$Declaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PDeclaration pdeclarationNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pdeclarationNode2 = (PDeclaration)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pdeclarationNode2 != null)
	{
	  listNode3.add(pdeclarationNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new59() /* reduce ATerminal$Line */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PLine plineNode1;
        plineNode1 = (PLine)nodeArrayList1.get(0);
	if(plineNode1 != null)
	{
	  listNode2.add(plineNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new60() /* reduce ANonTerminal$Line */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PLine plineNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        plineNode2 = (PLine)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(plineNode2 != null)
	{
	  listNode3.add(plineNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {28, SHIFT, 1}, },
			{{-1, ERROR, 1}, {10, SHIFT, 4}, },
			{{-1, ERROR, 2}, {32, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 4}, {11, SHIFT, 5}, },
			{{-1, ERROR, 5}, {24, SHIFT, 6}, },
			{{-1, REDUCE, 2}, {2, SHIFT, 7}, {3, SHIFT, 8}, {4, SHIFT, 9}, {22, SHIFT, 10}, {26, SHIFT, 11}, {27, SHIFT, 12}, {29, SHIFT, 13}, {30, SHIFT, 14}, {31, SHIFT, 15}, },
			{{-1, ERROR, 7}, {31, SHIFT, 23}, },
			{{-1, ERROR, 8}, {31, SHIFT, 25}, },
			{{-1, ERROR, 9}, {31, SHIFT, 27}, },
			{{-1, ERROR, 10}, {10, SHIFT, 29}, },
			{{-1, ERROR, 11}, {10, SHIFT, 30}, },
			{{-1, ERROR, 12}, {10, SHIFT, 31}, },
			{{-1, ERROR, 13}, {10, SHIFT, 32}, },
			{{-1, ERROR, 14}, {10, SHIFT, 33}, },
			{{-1, ERROR, 15}, {14, SHIFT, 34}, },
			{{-1, ERROR, 16}, {25, SHIFT, 35}, },
			{{-1, REDUCE, 57}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 19}, },
			{{-1, ERROR, 20}, {12, SHIFT, 36}, },
			{{-1, REDUCE, 3}, {2, SHIFT, 7}, {3, SHIFT, 8}, {4, SHIFT, 9}, {22, SHIFT, 10}, {26, SHIFT, 11}, {27, SHIFT, 12}, {29, SHIFT, 13}, {30, SHIFT, 14}, {31, SHIFT, 15}, },
			{{-1, REDUCE, 4}, {22, SHIFT, 10}, {26, SHIFT, 11}, {27, SHIFT, 12}, {29, SHIFT, 13}, {30, SHIFT, 14}, {31, SHIFT, 15}, },
			{{-1, ERROR, 23}, {12, SHIFT, 40}, {14, SHIFT, 34}, },
			{{-1, ERROR, 24}, {12, SHIFT, 41}, },
			{{-1, ERROR, 25}, {12, SHIFT, 42}, {14, SHIFT, 34}, },
			{{-1, ERROR, 26}, {12, SHIFT, 43}, },
			{{-1, ERROR, 27}, {12, SHIFT, 44}, {14, SHIFT, 34}, },
			{{-1, ERROR, 28}, {12, SHIFT, 45}, },
			{{-1, ERROR, 29}, {0, SHIFT, 46}, {1, SHIFT, 47}, {10, SHIFT, 48}, {31, SHIFT, 49}, },
			{{-1, ERROR, 30}, {0, SHIFT, 53}, {1, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, ERROR, 31}, {0, SHIFT, 56}, {1, SHIFT, 57}, {31, SHIFT, 58}, },
			{{-1, ERROR, 32}, {0, SHIFT, 46}, {1, SHIFT, 47}, {10, SHIFT, 48}, {31, SHIFT, 49}, },
			{{-1, ERROR, 33}, {31, SHIFT, 60}, },
			{{-1, ERROR, 34}, {0, SHIFT, 61}, {1, SHIFT, 62}, {10, SHIFT, 63}, {31, SHIFT, 64}, },
			{{-1, REDUCE, 1}, },
			{{-1, REDUCE, 20}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 5}, {22, SHIFT, 10}, {26, SHIFT, 11}, {27, SHIFT, 12}, {29, SHIFT, 13}, {30, SHIFT, 14}, {31, SHIFT, 15}, },
			{{-1, REDUCE, 60}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 41}, },
			{{-1, ERROR, 48}, {0, SHIFT, 46}, {1, SHIFT, 47}, {10, SHIFT, 48}, {31, SHIFT, 49}, },
			{{-1, REDUCE, 39}, },
			{{-1, ERROR, 50}, {11, SHIFT, 69}, {20, SHIFT, 70}, {21, SHIFT, 71}, },
			{{-1, REDUCE, 29}, },
			{{-1, ERROR, 52}, {13, SHIFT, 72}, {15, SHIFT, 73}, {16, SHIFT, 74}, {17, SHIFT, 75}, {18, SHIFT, 76}, {19, SHIFT, 77}, },
			{{-1, ERROR, 53}, {11, SHIFT, 78}, },
			{{-1, ERROR, 54}, {11, SHIFT, 79}, },
			{{-1, ERROR, 55}, {11, SHIFT, 80}, },
			{{-1, ERROR, 56}, {11, SHIFT, 81}, },
			{{-1, ERROR, 57}, {11, SHIFT, 82}, },
			{{-1, ERROR, 58}, {11, SHIFT, 83}, },
			{{-1, ERROR, 59}, {11, SHIFT, 84}, {20, SHIFT, 70}, {21, SHIFT, 71}, },
			{{-1, ERROR, 60}, {11, SHIFT, 85}, },
			{{-1, REDUCE, 54}, },
			{{-1, REDUCE, 45}, },
			{{-1, ERROR, 63}, {0, SHIFT, 61}, {10, SHIFT, 63}, {31, SHIFT, 64}, },
			{{-1, REDUCE, 55}, },
			{{-1, REDUCE, 46}, {5, SHIFT, 87}, {6, SHIFT, 88}, },
			{{-1, REDUCE, 47}, {7, SHIFT, 89}, {8, SHIFT, 90}, {9, SHIFT, 91}, },
			{{-1, REDUCE, 50}, },
			{{-1, ERROR, 68}, {11, SHIFT, 92}, {20, SHIFT, 70}, {21, SHIFT, 71}, },
			{{-1, ERROR, 69}, {24, SHIFT, 93}, },
			{{-1, ERROR, 70}, {0, SHIFT, 46}, {1, SHIFT, 47}, {10, SHIFT, 48}, {31, SHIFT, 49}, },
			{{-1, ERROR, 71}, {0, SHIFT, 46}, {1, SHIFT, 47}, {10, SHIFT, 48}, {31, SHIFT, 49}, },
			{{-1, ERROR, 72}, {0, SHIFT, 96}, {1, SHIFT, 97}, {31, SHIFT, 98}, },
			{{-1, ERROR, 73}, {0, SHIFT, 96}, {1, SHIFT, 97}, {31, SHIFT, 98}, },
			{{-1, ERROR, 74}, {0, SHIFT, 96}, {1, SHIFT, 97}, {31, SHIFT, 98}, },
			{{-1, ERROR, 75}, {0, SHIFT, 96}, {1, SHIFT, 97}, {31, SHIFT, 98}, },
			{{-1, ERROR, 76}, {0, SHIFT, 96}, {1, SHIFT, 97}, {31, SHIFT, 98}, },
			{{-1, ERROR, 77}, {0, SHIFT, 96}, {1, SHIFT, 97}, {31, SHIFT, 98}, },
			{{-1, ERROR, 78}, {12, SHIFT, 105}, },
			{{-1, ERROR, 79}, {12, SHIFT, 106}, },
			{{-1, ERROR, 80}, {12, SHIFT, 107}, },
			{{-1, ERROR, 81}, {12, SHIFT, 108}, },
			{{-1, ERROR, 82}, {12, SHIFT, 109}, },
			{{-1, ERROR, 83}, {12, SHIFT, 110}, },
			{{-1, ERROR, 84}, {24, SHIFT, 111}, },
			{{-1, ERROR, 85}, {12, SHIFT, 112}, },
			{{-1, ERROR, 86}, {5, SHIFT, 87}, {6, SHIFT, 88}, {11, SHIFT, 113}, },
			{{-1, ERROR, 87}, {0, SHIFT, 61}, {10, SHIFT, 63}, {31, SHIFT, 64}, },
			{{-1, ERROR, 88}, {0, SHIFT, 61}, {10, SHIFT, 63}, {31, SHIFT, 64}, },
			{{-1, ERROR, 89}, {0, SHIFT, 61}, {10, SHIFT, 63}, {31, SHIFT, 64}, },
			{{-1, ERROR, 90}, {0, SHIFT, 61}, {10, SHIFT, 63}, {31, SHIFT, 64}, },
			{{-1, ERROR, 91}, {0, SHIFT, 61}, {10, SHIFT, 63}, {31, SHIFT, 64}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 93}, {22, SHIFT, 10}, {25, SHIFT, 119}, {26, SHIFT, 11}, {27, SHIFT, 12}, {29, SHIFT, 13}, {30, SHIFT, 14}, {31, SHIFT, 15}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 34}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 12}, },
			{{-1, ERROR, 111}, {22, SHIFT, 10}, {25, SHIFT, 121}, {26, SHIFT, 11}, {27, SHIFT, 12}, {29, SHIFT, 13}, {30, SHIFT, 14}, {31, SHIFT, 15}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 48}, {7, SHIFT, 89}, {8, SHIFT, 90}, {9, SHIFT, 91}, },
			{{-1, REDUCE, 49}, {7, SHIFT, 89}, {8, SHIFT, 90}, {9, SHIFT, 91}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 53}, },
			{{-1, REDUCE, 21}, {23, SHIFT, 123}, },
			{{-1, ERROR, 120}, {22, SHIFT, 10}, {25, SHIFT, 125}, {26, SHIFT, 11}, {27, SHIFT, 12}, {29, SHIFT, 13}, {30, SHIFT, 14}, {31, SHIFT, 15}, },
			{{-1, REDUCE, 25}, },
			{{-1, ERROR, 122}, {22, SHIFT, 10}, {25, SHIFT, 126}, {26, SHIFT, 11}, {27, SHIFT, 12}, {29, SHIFT, 13}, {30, SHIFT, 14}, {31, SHIFT, 15}, },
			{{-1, ERROR, 123}, {24, SHIFT, 127}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 22}, {23, SHIFT, 123}, },
			{{-1, REDUCE, 26}, },
			{{-1, ERROR, 127}, {22, SHIFT, 10}, {25, SHIFT, 129}, {26, SHIFT, 11}, {27, SHIFT, 12}, {29, SHIFT, 13}, {30, SHIFT, 14}, {31, SHIFT, 15}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 27}, },
			{{-1, ERROR, 130}, {22, SHIFT, 10}, {25, SHIFT, 131}, {26, SHIFT, 11}, {27, SHIFT, 12}, {29, SHIFT, 13}, {30, SHIFT, 14}, {31, SHIFT, 15}, },
			{{-1, REDUCE, 28}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 3}, },
			{{-1, 16}, },
			{{-1, 17}, {21, 37}, },
			{{-1, 18}, {22, 39}, {38, 39}, {120, 39}, {122, 39}, {130, 39}, },
			{{-1, 19}, },
			{{-1, 124}, {125, 128}, },
			{{-1, 50}, {32, 59}, {48, 68}, },
			{{-1, 51}, {70, 94}, {71, 95}, },
			{{-1, 52}, },
			{{-1, 99}, {73, 100}, {74, 101}, {75, 102}, {76, 103}, {77, 104}, },
			{{-1, 20}, {7, 24}, {8, 26}, {9, 28}, },
			{{-1, 65}, {63, 86}, },
			{{-1, 66}, {87, 114}, {88, 115}, },
			{{-1, 67}, {89, 116}, {90, 117}, {91, 118}, },
			{{-1, 21}, },
			{{-1, 22}, {21, 38}, {93, 120}, {111, 122}, {127, 130}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'main'",
			"expecting: '('",
			"expecting: EOF",
			"expecting: ')'",
			"expecting: '{'",
			"expecting: 'int', 'double', 'string', 'if', '}', 'print', 'println', 'while', 'input', var",
			"expecting: var",
			"expecting: '='",
			"expecting: '}'",
			"expecting: 'if', '}', 'print', 'println', 'while', 'input', var",
			"expecting: ';'",
			"expecting: ';', '='",
			"expecting: number, string literal, '(', var",
			"expecting: number, string literal, var",
			"expecting: '==', '!=', '<=', '>=', '<', '>'",
			"expecting: ')', '&&', '||'",
			"expecting: '+', '-', '*', '/', '%', ')', ';'",
			"expecting: number, '(', var",
			"expecting: '+', '-', ';'",
			"expecting: '+', '-', ')'",
			"expecting: 'if', 'else', '}', 'print', 'println', 'while', 'input', var",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 2, 3, 4, 5, 6, 6, 6, 1, 1, 1, 1, 1, 7, 8, 5, 9, 9, 10, 5, 9, 11, 10, 11, 10, 11, 10, 12, 13, 13, 12, 6, 12, 2, 9, 5, 9, 9, 5, 5, 5, 5, 5, 5, 14, 14, 12, 14, 15, 15, 14, 3, 3, 3, 3, 3, 3, 15, 3, 16, 10, 17, 16, 18, 16, 16, 15, 4, 12, 12, 13, 13, 13, 13, 13, 13, 10, 10, 10, 10, 10, 10, 4, 10, 19, 17, 17, 17, 17, 17, 15, 9, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 9, 9, 9, 9, 9, 9, 9, 9, 16, 16, 16, 16, 16, 16, 20, 9, 9, 9, 4, 9, 20, 9, 9, 9, 9, 9, 9, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
